language: php

sudo: true

php:
  - 7.1

# Spryker required extensions
before_install:
  # Redis is pre-installed on Travis, just enable it
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Add sury repo
  - sudo add-apt-repository ppa:ondrej/php -y # "-y" for skipping "Enter" reuqired message
  - sudo apt-get update

  # Install other required etensions
  - sudo apt-get install php7.1-gmp
  - sudo apt-get install php7.1-bz2
  # - sudo apt-get install php7.1-bcmath

  # Debug: current config
  - php-config --configure-options

install:
  - composer install

  # prepare projects

  # ShopSys - require Beta Access, request here: https://www.shopsys-framework.com/
  # - git clone git@git.shopsys-framework.com:shopsys/shopsys-framework.git --depth 1 project/shopsys
  # - git -C project/shopsys checkout 829cfde7

  # Sylius
  - git clone https://github.com/Sylius/Sylius.git --depth 1 --single-branch --branch v1.0.0-beta.3 project/sylius

  # Spryker
  - git clone https://github.com/spryker/demoshop --depth 1 --single-branch --branch 2.14 project/spryker
  - composer install --working-dir project/spryker

script:
  - bin/analyze
  # EasyCodingStandard checks
  - composer ecs-basic
  - composer psr2-basic
  # PHPStan
  - composer

notifications:
  email: never
