services:
    _defaults:
        autowire: true

    TomasVotruba\ShopsysAnalysis\:
        resource: '../../src'

    # Symfony Console
    Symfony\Component\Console\Application:
        calls:
            - ['add', ['@TomasVotruba\ShopsysAnalysis\Command\AnalyzeCommand']]
            - ['setDefaultCommand', ['analyze', true]]

    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Style\SymfonyStyle: ~


    # alias required for SymfonyStyle
    Symfony\Component\Console\Output\OutputInterface:
        alias: Symfony\Component\Console\Output\ConsoleOutput
